@startuml
'https://plantuml.com/sequence-diagram

/'autonumber'/


User -> api
activate api

       api -> "service RMI"
       activate "service RMI"

           "service RMI" -> bd
           activate bd

           "service RMI" <-- bd
           deactivate bd

       api <-- "service RMI"
       deactivate "service RMI"

User <-- api
deactivate api


User -> api
activate api

       api -> "service RMI"
       activate "service RMI"

           database bd
           "service RMI" -> bd
           activate bd

           "service RMI" <-- bd
           deactivate bd

       api <-- "service RMI"
       deactivate "service RMI"

User <-- api
deactivate api



@enduml